[project]
name = "crovio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "pydantic>=2.12.4",
    "pytest>=9.0.1",
    "sqlalchemy>=2.0.44",
]
